name: CI/CD Flutter - APK a Storage y Web a Docker
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Configurar Entorno
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 2. Compilar APK y Web
      - name: Build APK & Web
        run: |
          flutter pub get
          flutter build apk --release
          flutter build web --release

      # 3. Subir APK a Supabase Storage
      - name: Upload APK to Supabase
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            -H "x-upsert: true" \
            --data-binary "@build/app/outputs/flutter-apk/app-release.apk" \
            "${{ secrets.SUPABASE_URL }}/storage/v1/object/instaladores/app-release.apk"

      # 4. Login en Docker Hub y subir imagen Web
      - name: Docker Login & Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flutter-front:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flutter-front:latest